// ═══════════════════════════════════════════════════════════
// TOKYO ADVENTURE PATHS
// Each main landmark has 3 predetermined adventure routes
// Each route visits 6 sub-locations before reaching the main destination
// ═══════════════════════════════════════════════════════════

const ADVENTURE_PATHS = {
    // ═══════════════════════════════════════════════════════════
    // 1. SENSO-JI TEMPLE - 3 ADVENTURE ROUTES
    // ═══════════════════════════════════════════════════════════
    'Senso-ji Temple': [
        {
            pathId: 'sensoji_path_1',
            name: 'Eastern River Approach',
            difficulty: 'medium',
            totalDistance: '850m',
            description: 'Start from Sumida River, explore the waterfront and traditional streets',
            waypoints: [
                {
                    order: 1,
                    id: 'asakusa_sumida',
                    type: 'viewpoint',
                    name: 'Sumida River Walk',
                    coords: { lat: 35.7145, lng: 139.8015 },
                    heading: 270,
                    emoji: '🌊',
                    description:
                        'Start your journey at the historic Sumida River. Tokyo Skytree towers in the distance.',
                    task: 'Take a moment to observe the traditional yakatabune boats',
                    reward: 40,
                },
                {
                    order: 2,
                    id: 'asakusa_river_shrine',
                    type: 'cultural',
                    name: 'Komagata Bridge & Shrine',
                    coords: { lat: 35.7125, lng: 139.7995 },
                    heading: 250,
                    emoji: '⛩️',
                    description: 'Small riverside shrine protecting travelers crossing the bridge.',
                    task: 'Find the stone lanterns donated by river merchants',
                    reward: 35,
                },
                {
                    order: 3,
                    id: 'asakusa_side_street',
                    type: 'secret',
                    name: 'Hoppy Street (Denki Gai)',
                    coords: { lat: 35.7118, lng: 139.7978 },
                    heading: 230,
                    emoji: '🏮',
                    description:
                        'Hidden izakaya alley where locals drink Hoppy (beer-like beverage).',
                    task: 'Count the red lanterns in this narrow alley',
                    reward: 50,
                    secret: true,
                },
                {
                    order: 4,
                    id: 'asakusa_denpoin',
                    type: 'secret',
                    name: 'Denpoin Garden (Exterior)',
                    coords: { lat: 35.7152, lng: 139.7953 },
                    heading: 180,
                    emoji: '🌸',
                    description:
                        "The hidden temple garden's outer walls. Few tourists know this exists.",
                    task: 'Find the ancient temple bell visible from the street',
                    reward: 55,
                    secret: true,
                },
                {
                    order: 5,
                    id: 'asakusa_nakamise',
                    type: 'tourist',
                    name: 'Nakamise Shopping Street',
                    coords: { lat: 35.7115, lng: 139.7963 },
                    heading: 160,
                    emoji: '🏮',
                    description:
                        'Historic 250m shopping arcade. 90+ traditional shops from Edo period.',
                    task: 'Browse the traditional crafts and try ningyo-yaki sweets',
                    reward: 50,
                },
                {
                    order: 6,
                    id: 'asakusa_kaminarimon',
                    type: 'tourist',
                    name: 'Kaminarimon (Thunder Gate)',
                    coords: { lat: 35.7109, lng: 139.7965 },
                    heading: 0,
                    emoji: '🏮',
                    description:
                        'The iconic entrance! Stand beneath the massive 700kg red lantern.',
                    task: 'Photograph the thunder god and wind god statues',
                    reward: 45,
                },
            ],
            finalDestination: {
                name: 'Senso-ji Main Hall',
                coords: { lat: 35.7148, lng: 139.7967 },
                heading: 0,
                emoji: '⛩️',
                description: "You've arrived! Tokyo's oldest temple awaits.",
                reward: 100,
            },
        },

        {
            pathId: 'sensoji_path_2',
            name: 'Traditional Shopping Route',
            difficulty: 'easy',
            totalDistance: '650m',
            description: 'Follow the main pilgrimage path through shopping streets',
            waypoints: [
                {
                    order: 1,
                    id: 'asakusa_ramen_start',
                    type: 'food',
                    name: 'Ramen Yoroiya',
                    coords: { lat: 35.7118, lng: 139.7955 },
                    heading: 45,
                    emoji: '🍜',
                    description: 'Start with breakfast! Family-run ramen shop since 1950s.',
                    task: 'Fuel up for your adventure with chicken broth ramen',
                    reward: 45,
                },
                {
                    order: 2,
                    id: 'asakusa_side_shrine',
                    type: 'cultural',
                    name: 'Asakusa Shrine',
                    coords: { lat: 35.715, lng: 139.7975 },
                    heading: 320,
                    emoji: '⛩️',
                    description: 'Often missed Shinto shrine next to the Buddhist temple.',
                    task: "Watch for traditional wedding ceremonies if you're lucky!",
                    reward: 40,
                },
                {
                    order: 3,
                    id: 'asakusa_nitenmon',
                    type: 'cultural',
                    name: 'Nitenmon Gate (East Gate)',
                    coords: { lat: 35.7155, lng: 139.797 },
                    heading: 270,
                    emoji: '🏯',
                    description: 'Original Edo-era gate, less crowded than Kaminarimon.',
                    task: 'Find the guardian deity statues hidden in the gate',
                    reward: 35,
                },
                {
                    order: 4,
                    id: 'asakusa_incense',
                    type: 'cultural',
                    name: 'Incense Burner Plaza',
                    coords: { lat: 35.7145, lng: 139.7965 },
                    heading: 180,
                    emoji: '🔥',
                    description:
                        'Purification ritual area. Waft smoke over yourself for good health.',
                    task: 'Participate in the traditional purification ritual',
                    reward: 30,
                },
                {
                    order: 5,
                    id: 'asakusa_hozomon',
                    type: 'cultural',
                    name: 'Hozomon Gate',
                    coords: { lat: 35.7143, lng: 139.7964 },
                    heading: 0,
                    emoji: '⛩️',
                    description: 'Inner gate with giant straw sandals on the back wall.',
                    task: 'Walk through and look back to see the 4.5m sandals!',
                    reward: 40,
                },
                {
                    order: 6,
                    id: 'asakusa_pagoda',
                    type: 'tourist',
                    name: 'Five-Story Pagoda',
                    coords: { lat: 35.714, lng: 139.797 },
                    heading: 90,
                    emoji: '🗼',
                    description: "53-meter tall pagoda, one of Tokyo's tallest.",
                    task: 'Find the best angle to photograph pagoda and main hall together',
                    reward: 45,
                },
            ],
            finalDestination: {
                name: 'Senso-ji Main Hall',
                coords: { lat: 35.7148, lng: 139.7967 },
                heading: 0,
                emoji: '⛩️',
                description: 'Complete your pilgrimage at the main hall!',
                reward: 100,
            },
        },

        {
            pathId: 'sensoji_path_3',
            name: 'Hidden Backstreets Path',
            difficulty: 'hard',
            totalDistance: '920m',
            description: 'Secret route through local neighborhoods and hidden temples',
            waypoints: [
                {
                    order: 1,
                    id: 'asakusa_secret_start',
                    type: 'secret',
                    name: 'Senzoku Street Entrance',
                    coords: { lat: 35.7105, lng: 139.794 },
                    heading: 45,
                    emoji: '🏘️',
                    description: 'Quiet residential area where locals live. Authentic Tokyo.',
                    task: 'Explore the small local shops hidden from tourist routes',
                    reward: 50,
                    secret: true,
                },
                {
                    order: 2,
                    id: 'asakusa_local_shrine',
                    type: 'cultural',
                    name: 'Imado Shrine',
                    coords: { lat: 35.7125, lng: 139.7935 },
                    heading: 30,
                    emoji: '⛩️',
                    description: 'Birthplace of the lucky cat (maneki-neko)! Hidden local shrine.',
                    task: 'Find the paired cat statues at the shrine entrance',
                    reward: 55,
                    secret: true,
                },
                {
                    order: 3,
                    id: 'asakusa_craft_street',
                    type: 'secret',
                    name: 'Kappabashi Kitchen Town',
                    coords: { lat: 35.7122, lng: 139.7925 },
                    heading: 70,
                    emoji: '🔪',
                    description: 'Street of restaurant supply shops. Fake food samples look real!',
                    task: 'Window shop the incredibly realistic plastic sushi displays',
                    reward: 45,
                },
                {
                    order: 4,
                    id: 'asakusa_temple_back',
                    type: 'viewpoint',
                    name: 'Senso-ji West Approach',
                    coords: { lat: 35.7135, lng: 139.7945 },
                    heading: 90,
                    emoji: '🏯',
                    description: 'Quiet temple entrance used by monks and locals.',
                    task: 'Listen for temple bells and monk chanting',
                    reward: 40,
                },
                {
                    order: 5,
                    id: 'asakusa_garden_path',
                    type: 'secret',
                    name: 'Temple Garden Path',
                    coords: { lat: 35.7148, lng: 139.795 },
                    heading: 110,
                    emoji: '🌿',
                    description: 'Rarely used garden path with ancient stone lanterns.',
                    task: 'Count the stone lanterns along this peaceful path',
                    reward: 50,
                    secret: true,
                },
                {
                    order: 6,
                    id: 'asakusa_fortune_stalls',
                    type: 'cultural',
                    name: 'Omikuji Fortune Area',
                    coords: { lat: 35.7146, lng: 139.796 },
                    heading: 135,
                    emoji: '📜',
                    description: "Draw your fortune! If it's bad luck, tie it to the rack.",
                    task: 'Try your luck with an omikuji fortune slip (100 yen)',
                    reward: 35,
                },
            ],
            finalDestination: {
                name: 'Senso-ji Main Hall',
                coords: { lat: 35.7148, lng: 139.7967 },
                heading: 0,
                emoji: '⛩️',
                description: 'The secret route ends at the sacred main hall!',
                reward: 100,
            },
        },
    ],

    // ═══════════════════════════════════════════════════════════
    // 2. TOKYO TOWER - 3 ADVENTURE ROUTES
    // ═══════════════════════════════════════════════════════════
    'Tokyo Tower': [
        {
            pathId: 'tower_path_1',
            name: 'Temple & Park Route',
            difficulty: 'easy',
            totalDistance: '750m',
            description: 'Peaceful walk through Shiba Park and historic temple grounds',
            waypoints: [
                {
                    order: 1,
                    id: 'tower_shiba_entrance',
                    type: 'viewpoint',
                    name: 'Shiba Park Main Entrance',
                    coords: { lat: 35.655, lng: 139.746 },
                    heading: 0,
                    emoji: '🌳',
                    description:
                        "Start in one of Tokyo's oldest parks (1873). Cherry blossoms in spring!",
                    task: 'Find the perfect angle to frame Tokyo Tower through the trees',
                    reward: 35,
                },
                {
                    order: 2,
                    id: 'tower_zojoji_gate',
                    type: 'cultural',
                    name: 'Zojoji Temple Sangedatsumon Gate',
                    coords: { lat: 35.6565, lng: 139.746 },
                    heading: 20,
                    emoji: '⛩️',
                    description: 'Oldest wooden building in Tokyo (1622). Massive wooden gate.',
                    task: 'Pass through the gate that leads to enlightenment',
                    reward: 45,
                },
                {
                    order: 3,
                    id: 'tower_zojoji_main',
                    type: 'cultural',
                    name: 'Zojoji Temple Main Hall',
                    coords: { lat: 35.6574, lng: 139.7464 },
                    heading: 90,
                    emoji: '⛩️',
                    description: 'Tokugawa shogun family temple. 6 shoguns buried here!',
                    task: 'Look for Tokyo Tower dramatically rising behind the temple',
                    reward: 50,
                },
                {
                    order: 4,
                    id: 'tower_jizo_statues',
                    type: 'cultural',
                    name: 'Unborn Children Jizo Statues',
                    coords: { lat: 35.657, lng: 139.7455 },
                    heading: 45,
                    emoji: '🙏',
                    description: 'Hundreds of small Jizo statues with knitted hats. Very moving.',
                    task: 'Pay respects at this peaceful memorial garden',
                    reward: 40,
                },
                {
                    order: 5,
                    id: 'tower_prince_park',
                    type: 'viewpoint',
                    name: 'Prince Shiba Park',
                    coords: { lat: 35.6582, lng: 139.7468 },
                    heading: 60,
                    emoji: '📸',
                    description:
                        'Best photo spot! Classic angle with temple foreground, tower behind.',
                    task: 'Capture the iconic temple-tower composition',
                    reward: 45,
                },
                {
                    order: 6,
                    id: 'tower_approach',
                    type: 'tourist',
                    name: 'Tower Base Plaza',
                    coords: { lat: 35.658, lng: 139.7452 },
                    heading: 80,
                    emoji: '📸',
                    description: 'Standing directly beneath the tower! Look straight up.',
                    task: "Experience the tower's massive scale from below",
                    reward: 40,
                },
            ],
            finalDestination: {
                name: 'Tokyo Tower Main Observatory',
                coords: { lat: 35.6586, lng: 139.7454 },
                heading: 0,
                emoji: '🗼',
                description: 'Ascend the iconic orange tower for 360° views!',
                reward: 100,
            },
        },

        {
            pathId: 'tower_path_2',
            name: 'Modern City Route',
            difficulty: 'medium',
            totalDistance: '820m',
            description: 'Through modern Minato district with shopping and skyscrapers',
            waypoints: [
                {
                    order: 1,
                    id: 'tower_roppongi_approach',
                    type: 'viewpoint',
                    name: 'Azabudai Hills View',
                    coords: { lat: 35.6555, lng: 139.7425 },
                    heading: 60,
                    emoji: '🏙️',
                    description: 'New development area. Modern Tokyo at its finest.',
                    task: 'Spot Tokyo Tower peeking between the buildings',
                    reward: 35,
                },
                {
                    order: 2,
                    id: 'tower_russian_embassy',
                    type: 'tourist',
                    name: 'Russian Embassy Street',
                    coords: { lat: 35.6562, lng: 139.7435 },
                    heading: 40,
                    emoji: '🏛️',
                    description: 'Diplomatic quarter. Beautiful European architecture.',
                    task: 'Walk the tree-lined embassy district',
                    reward: 30,
                },
                {
                    order: 3,
                    id: 'tower_tofu_ukai',
                    type: 'food',
                    name: 'Tofu Ukai Restaurant',
                    coords: { lat: 35.6572, lng: 139.7442 },
                    heading: 50,
                    emoji: '🍱',
                    description: 'Elegant traditional mansion restaurant. Tofu kaiseki cuisine.',
                    task: 'Admire the traditional Japanese architecture',
                    reward: 40,
                },
                {
                    order: 4,
                    id: 'tower_jizodori_secret',
                    type: 'secret',
                    name: 'Jizo-dori Shopping Street',
                    coords: { lat: 35.6555, lng: 139.7435 },
                    heading: 80,
                    emoji: '🏪',
                    description: 'Hidden local shopping street! No tourists here.',
                    task: 'Browse authentic neighborhood shops',
                    reward: 55,
                    secret: true,
                },
                {
                    order: 5,
                    id: 'tower_stadium_view',
                    type: 'viewpoint',
                    name: 'Rugby Stadium View Point',
                    coords: { lat: 35.6565, lng: 139.747 },
                    heading: 340,
                    emoji: '🏉',
                    description: 'See the stadium that hosted 2019 Rugby World Cup.',
                    task: 'Find the tower rising beyond the stadium',
                    reward: 35,
                },
                {
                    order: 6,
                    id: 'tower_foottown',
                    type: 'tourist',
                    name: 'Tower FootTown Building',
                    coords: { lat: 35.6584, lng: 139.7456 },
                    heading: 0,
                    emoji: '🏢',
                    description:
                        "Tower's base building with shops, aquarium, and One Piece exhibit.",
                    task: 'Enter through the main entrance',
                    reward: 40,
                },
            ],
            finalDestination: {
                name: 'Tokyo Tower Main Observatory',
                coords: { lat: 35.6586, lng: 139.7454 },
                heading: 0,
                emoji: '🗼',
                description: 'Ride the elevator 150 meters up!',
                reward: 100,
            },
        },

        {
            pathId: 'tower_path_3',
            name: 'Hidden Backstreets',
            difficulty: 'hard',
            totalDistance: '940m',
            description: 'Secret local paths through residential Shiba neighborhood',
            waypoints: [
                {
                    order: 1,
                    id: 'tower_secret_shrine',
                    type: 'secret',
                    name: 'Maruyama Shrine',
                    coords: { lat: 35.6545, lng: 139.7445 },
                    heading: 30,
                    emoji: '⛩️',
                    description: 'Tiny neighborhood shrine unknown to tourists.',
                    task: 'Ring the bell and pay respects',
                    reward: 50,
                    secret: true,
                },
                {
                    order: 2,
                    id: 'tower_local_street',
                    type: 'secret',
                    name: 'Shiba Residential Quarter',
                    coords: { lat: 35.6558, lng: 139.7448 },
                    heading: 20,
                    emoji: '🏘️',
                    description: 'Authentic Tokyo neighborhood. How locals really live.',
                    task: 'Experience residential Tokyo away from tourist zones',
                    reward: 45,
                    secret: true,
                },
                {
                    order: 3,
                    id: 'tower_old_houses',
                    type: 'viewpoint',
                    name: 'Traditional House Street',
                    coords: { lat: 35.6568, lng: 139.745 },
                    heading: 350,
                    emoji: '🏡',
                    description: 'Old wooden houses survived WWII bombing. Rare sight!',
                    task: 'Find houses with traditional tile roofs',
                    reward: 50,
                },
                {
                    order: 4,
                    id: 'tower_cemetery',
                    type: 'cultural',
                    name: 'Zojoji Cemetery Approach',
                    coords: { lat: 35.6572, lng: 139.7458 },
                    heading: 330,
                    emoji: '🪦',
                    description:
                        'Historic cemetery of samurai and nobles. Peaceful and respectful.',
                    task: 'Walk quietly through history',
                    reward: 40,
                },
                {
                    order: 5,
                    id: 'tower_back_entrance',
                    type: 'secret',
                    name: 'Tower Back Entrance',
                    coords: { lat: 35.6578, lng: 139.746 },
                    heading: 340,
                    emoji: '🚪',
                    description: 'Secret entrance used by locals to avoid crowds.',
                    task: 'Find the back way up',
                    reward: 55,
                    secret: true,
                },
                {
                    order: 6,
                    id: 'tower_maintenance',
                    type: 'viewpoint',
                    name: 'Tower Maintenance View',
                    coords: { lat: 35.6582, lng: 139.745 },
                    heading: 90,
                    emoji: '🔧',
                    description: "See the tower's support structure up close. Engineering marvel!",
                    task: 'Appreciate the steel framework',
                    reward: 40,
                },
            ],
            finalDestination: {
                name: 'Tokyo Tower Main Observatory',
                coords: { lat: 35.6586, lng: 139.7454 },
                heading: 0,
                emoji: '🗼',
                description: 'You found the secret route to the top!',
                reward: 100,
            },
        },
    ],
};

// Additional locations will be added in separate calls due to file size
